<template>
  <div>
    <header>
      <v-btn
        v-if="showSched"
        @click="getSchedAll(), (checkedGroup = '')"
        color="warning"
        dark
      >
        Назад
      </v-btn>

      <v-card class="card">
        <v-banner sticky class="text-center">
          <span :class="!$vuetify.breakpoint.mobile ? 'display-1' : null">
            Расписание {{ checkedGroup !== "" ? `группы ${checkedGroup}` : "" }}
          </span>
        </v-banner>
      </v-card>
    </header>
    <div class="sched-container">
      <div v-if="showSched">
        <div
          class="sched-card"
          v-for="gsched in groupSchedByDays"
          :key="JSON.stringify(gsched)"
        >
          {{ gsched[0].SUBJECT }}
          <v-card>
            <v-simple-table>
              <template v-slot:default>
                <thead>
                  <tr>
                    <th class="text-left">№</th>
                    <th class="text-left">Аудитория</th>
                    <th class="text-left">Предмет</th>
                    <th class="text-left">Тип</th>
                    <th class="text-left">Преподаватель</th>
                  </tr>
                </thead>
                <tbody>
                  <tr
                    v-for="item in gsched"
                    :key="`${item.SUBJECT}-${item.LES}-${item.SUBG}`"
                  >
                    <td>{{ item.LES }}</td>
                    <td>{{ item.AUD }}</td>
                    <td>{{ item.POST }}</td>
                    <td>{{ item.NAME }}</td>
                    <td>{{ item.SUBG }}</td>
                  </tr>
                </tbody>
              </template>
            </v-simple-table>
          </v-card>
        </div>
      </div>
      <div
        v-else
        v-for="key in keys"
        cols="12"
        md="10"
        offset-md="1"
        :key="key"
      >
        <v-card
          class="group-card"
          @click="getSchedByGroup(key, sched), (checkedGroup = key)"
          >{{ key }}
        </v-card>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "edu-schedule",
  data() {
    return {
      keys: [],
      showSched: false,
      checkedGroup: "",
      sched: [
        {
          GROUP: "ДВ-11",
          DAY: " 1",
          LES: " 2",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Устименко Д.Л.",
          POST: "История",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 1",
          LES: " 3",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Устименко Д.Л.",
          POST: "История",
          NAME: " ПЗ",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 2",
          LES: " 2",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Инж. и комп. граф",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 2",
          LES: " 3",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Инж. и комп. граф",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 3",
          LES: " 2",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Алгебра и геометрия",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 3",
          LES: " 3",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Алгебра и геометрия",
          NAME: " ПЗ",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 4",
          LES: " 1",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Информатика",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 4",
          LES: " 2",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Информатика",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 4",
          LES: " 3",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Алгебра и геометрия",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 5",
          LES: " 2",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 5",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Колдынская Л.М.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 5",
          LES: " 3",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 5",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Колдынская Л.М.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 6",
          LES: " 2",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО 2",
          NAME: " ПЗ",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДВ-11",
          DAY: " 6",
          LES: " 3",
          AUD: " 308",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО 2",
          NAME: " ПЗ",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 1",
          LES: " 1",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 1",
          LES: " 1",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Колдынская Л.М.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 1",
          LES: " 2",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Информатика",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 1",
          LES: " 3",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Информатика",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 2",
          LES: " 2",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 2",
          LES: " 3",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " Русский язык и КР",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 3",
          LES: " 2",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 3",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Колдынская Л.М.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 3",
          LES: " 3",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Устименко Д.Л.",
          POST: "Философия",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 4",
          LES: " 1",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО 2",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 4",
          LES: " 2",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Устименко Д.Л.",
          POST: "История",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 5",
          LES: " 1",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО 2",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 5",
          LES: " 2",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Костецкая Г.С.",
          POST: "Высшая математика",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-11",
          DAY: " 5",
          LES: " 3",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Костецкая Г.С.",
          POST: "Высшая математика",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 1",
          LES: " 1",
          AUD: " Ц-4",
          WEEK: " 2",
          SUBG: " Устименко Д.Л.",
          POST: "Искусство дел. отнош",
          NAME: "ПЗ",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 1",
          LES: " 2",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Информатика",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 1",
          LES: " 3",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Информатика",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 2",
          LES: " 2",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 2",
          LES: " 3",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " Русский язык и КР",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 3",
          LES: " 1",
          AUD: " Ц-4",
          WEEK: " 2",
          SUBG: " Костецкая Г.С.",
          POST: "Высшая математика",
          NAME: " ПЗ",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 3",
          LES: " 2",
          AUD: " Ц-4",
          WEEK: " 2",
          SUBG: " Костецкая Г.С.",
          POST: "Высшая математика",
          NAME: " ПЗ",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 3",
          LES: " 3",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Устименко Д.Л.",
          POST: "Философия",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 4",
          LES: " 2",
          AUD: " Ц-4",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 4",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Колдынская Л.М.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 4",
          LES: " 3",
          AUD: " Ц-4",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 4",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Колдынская Л.М.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 5",
          LES: " 2",
          AUD: " Ц-4",
          WEEK: " 2",
          SUBG: " Устименко Д.Л.",
          POST: "История",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-12",
          DAY: " 5",
          LES: " 3",
          AUD: " Ц-4",
          WEEK: " 2",
          SUBG: " Устименко Д.Л.",
          POST: "История",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 1",
          LES: " 1",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Технологии языков прогр",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 1",
          LES: " 2",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Технологии языков прогр",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 1",
          LES: " 3",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Технологии языков прогр",
          NAME: " ПЗ",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 2",
          LES: " 1",
          AUD: " 306",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 2",
          LES: " 2",
          AUD: " 306",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО",
          NAME: " ПЗ",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 3",
          LES: " 1",
          AUD: " 306",
          WEEK: " 2",
          SUBG: " Светличная Н.О.",
          POST: " ИНО 2",
          NAME: " ПЗ",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 3",
          LES: " 2",
          AUD: " 306",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Вычислительная техника",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 3",
          LES: " 3",
          AUD: " 306",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Вычислительная техника",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 4",
          LES: " 1",
          AUD: " 306",
          WEEK: " 2",
          SUBG: " Ландышев В.А.",
          POST: " Мультимедиа технологии и протоколы",
          NAME: "лек.",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 4",
          LES: " 2",
          AUD: " 306",
          WEEK: " 2",
          SUBG: " Ландышев В.А.",
          POST: " Мультимедиа технологии и протоколы",
          NAME: "лек.",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДВ-21",
          DAY: " 5",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ершов В.В.",
          POST: "Электропитание КС и ВК",
          NAME: "лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДВ-21",
          DAY: " 5",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ершов В.В.",
          POST: "Электропитание КС и ВК",
          NAME: "лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДИ-21",
          DAY: " 1",
          LES: " 2",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Физ. осн. электроники",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 1",
          LES: " 3",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Физ. осн. электроники",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 2",
          LES: " 2",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Гаевская Л.А.",
          POST: " Физ. культура",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 2",
          LES: " 3",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Теор. эл. цепей",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 3",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Конкин Б.Б.",
          POST: " Физика",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 3",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Конкин Б.Б.",
          POST: " Физика",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 4",
          LES: " 1",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " ТВ и МС",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 4",
          LES: " 2",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Теор. эл. цепей",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 5",
          LES: " 2",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Гаевская Л.А.",
          POST: " Физ. культура",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-21",
          DAY: " 5",
          LES: " 3",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Гаевская Л.А.",
          POST: " Физ. культура",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 1",
          LES: " 2",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Физ. осн. электроники",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 1",
          LES: " 3",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Физ. осн. электроники",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 2",
          LES: " 1",
          AUD: " 302",
          WEEK: " 2",
          SUBG: " Гаевская Л.А.",
          POST: " Физ. культура",
          NAME: " ПЗ",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 2",
          LES: " 2",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Гаевская Л.А.",
          POST: " Физ. культура",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 2",
          LES: " 3",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Теор. эл. цепей",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 3",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Конкин Б.Б.",
          POST: " Физика",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 3",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Конкин Б.Б.",
          POST: " Физика",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 4",
          LES: " 1",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " ТВ и МС",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 4",
          LES: " 2",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Теор. эл. цепей",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 6",
          LES: " 2",
          AUD: " 310",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Физ. осн. электроники",
          NAME: " ЛР",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 6",
          LES: " 2",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Коршун А.М.",
          POST: " Физ. осн. электроники",
          NAME: " ЛР",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 6",
          LES: " 3",
          AUD: " 310",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Физ. осн. электроники",
          NAME: " ЛР",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДИ-22",
          DAY: " 6",
          LES: " 3",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Коршун А.М.",
          POST: " Физ. осн. электроники",
          NAME: " ЛР",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДП-31",
          DAY: " 1",
          LES: " 4",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Методы и средства проектирования ИС",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 1",
          LES: " 5",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Методы и средства проектирования ИС",
          NAME: " ПЗ",
          SUBJECT: "7-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 2",
          LES: " 4",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Методы и средства проектирования ИС",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 2",
          LES: " 5",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Методы и средства проектирования ИС",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 2",
          LES: " 6",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Швидченко С.А.",
          POST: "Методы и средства проектирования ИС",
          NAME: " ПЗ",
          SUBJECT: "8-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 3",
          LES: " 4",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Операционн. системы",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 3",
          LES: " 5",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Операционн. системы",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 4",
          LES: " 4",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Осн. комп. моделир",
          NAME: "лек.",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 4",
          LES: " 5",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Осн. комп. моделир",
          NAME: "лек.",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 4",
          LES: " 6",
          AUD: " 305",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Осн. комп. моделир",
          NAME: "ЛР",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 4",
          LES: " 6",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Соколов С.В",
          POST: " Осн. комп. моделир",
          NAME: "ЛР",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 5",
          LES: " 4",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Методы отладки и тестирования ПП",
          NAME: "лек.",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 5",
          LES: " 5",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Методы отладки и тестирования ПП",
          NAME: "лек.",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 5",
          LES: " 6",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Ткачук Е.О.",
          POST: " Методы отладки и тестирования ПП",
          NAME: "ПЗ",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-31",
          DAY: " 6",
          LES: " 1",
          AUD: " 214",
          WEEK: " 2",
          SUBG: " Рыбалко И.П.",
          POST: "Архитектура информационных систем",
          NAME: " лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДП-31",
          DAY: " 6",
          LES: " 2",
          AUD: " 214",
          WEEK: " 2",
          SUBG: " Рыбалко И.П.",
          POST: "Архитектура информационных систем",
          NAME: " лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДЗ-31",
          DAY: " 1",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Приемопередающие устройства",
          NAME: " ПЗ",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-31",
          DAY: " 1",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Приемопередающие устройства",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-31",
          DAY: " 2",
          LES: " 4",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Эл. магн. поля и волны",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 2",
          LES: " 5",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Эл. магн. поля и волны",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 3",
          LES: " 4",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Цифр. обр. сигн",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 3",
          LES: " 5",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Цифр. обр. сигн",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 3",
          LES: " 6",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Анализ случайных процессов",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 4",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Чикалов А.Н.",
          POST: "Схемотехника ТКУ",
          NAME: "ПЗ",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 4",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Приемопередающие устройства",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДЗ-31",
          DAY: " 5",
          LES: " 4",
          AUD: " 401",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Эл. магн. поля и волны",
          NAME: "ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 5",
          LES: " 5",
          AUD: " 401",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Эл. магн. поля и волны",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 5",
          LES: " 5",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Бородин А.В",
          POST: " Эл. магн. поля и волны",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 5",
          LES: " 6",
          AUD: " 401",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Эл. магн. поля и волны",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 5",
          LES: " 6",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Бородин А.В",
          POST: " Эл. магн. поля и волны",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 6",
          LES: " 1",
          AUD: " 101",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Цифр. обр. сигн",
          NAME: " ЛР",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 6",
          LES: " 1",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Конкин Б.Б.",
          POST: " Цифр. обр. сигн",
          NAME: " ЛР",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 6",
          LES: " 2",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Анализ случайных процессов",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДЗ-31",
          DAY: " 6",
          LES: " 3",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Анализ случайных процессов",
          NAME: "ПЗ",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДС-31",
          DAY: " 1",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Приемопередающие устройства",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДС-31",
          DAY: " 1",
          LES: " 6",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Приемопередающие устройства",
          NAME: " ПЗ",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДС-31",
          DAY: " 2",
          LES: " 4",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Эл. магн. поля и волны",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДС-31",
          DAY: " 2",
          LES: " 5",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Константинова Я.Б.",
          POST: "Эл. магн. поля и волны",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДС-31",
          DAY: " 3",
          LES: " 4",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Цифр. обр. сигн",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДС-31",
          DAY: " 3",
          LES: " 5",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Бородин А.В.",
          POST: "Цифр. обр. сигн",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДС-31",
          DAY: " 3",
          LES: " 6",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Анализ случайных процессов",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДС-31",
          DAY: " 4",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Приемопередающие устройства",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДС-31",
          DAY: " 4",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Чикалов А.Н.",
          POST: "Схемотехника ТКУ",
          NAME: "ПЗ",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДС-31",
          DAY: " 5",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Чикалов А.Н.",
          POST: "Схемотехника ТКУ",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДС-31",
          DAY: " 5",
          LES: " 4",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Соколов С.В.",
          POST: "Схемотехника ТКУ",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДС-31",
          DAY: " 5",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Чикалов А.Н.",
          POST: "Схемотехника ТКУ",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДС-31",
          DAY: " 5",
          LES: " 5",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Соколов С.В.",
          POST: "Схемотехника ТКУ",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДС-31",
          DAY: " 5",
          LES: " 6",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Чикалов А.Н.",
          POST: "Схемотехника ТКУ",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДС-31",
          DAY: " 5",
          LES: " 6",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Соколов С.В.",
          POST: "Схемотехника ТКУ",
          NAME: "ЛР",
          SUBJECT: "11-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДС-31",
          DAY: " 6",
          LES: " 1",
          AUD: " 306",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Анализ случайных процессов",
          NAME: "ПЗ",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " ДС-31",
          DAY: " 6",
          LES: " 2",
          AUD: " 402",
          WEEK: " 2",
          SUBG: " Ефимов С.В.",
          POST: " Анализ случайных процессов",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ОНП",
        },
        {
          GROUP: " В-31",
          DAY: "2",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " деканат",
          POST: " СОБРАНИЕ",
          NAME: "лек.",
          SUBJECT: "8-09-2020 дек",
        },
        {
          GROUP: "В-31",
          DAY: "2",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ефимов С.В.",
          POST: " Теория случайных процессов",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " В-31",
          DAY: "2",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ефимов С.В.",
          POST: " Теория случайных процессов",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " В-31",
          DAY: "3",
          LES: " 1",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Швидченко С.А.",
          POST: "Методы и средства проектирования ИС",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " В-31",
          DAY: "3",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Швидченко С.А.",
          POST: "Методы и средства проектирования ИС",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " В-31",
          DAY: "3",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Соколов С.В.",
          POST: "Схемотехника",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " В-31",
          DAY: "4",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Соколов С.В.",
          POST: "Схемотехника",
          NAME: "лек.",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " В-31",
          DAY: "4",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " В-31",
          DAY: "4",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "ПЗ",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " В-31",
          DAY: "5",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Головина И.В.",
          POST: " Экономика",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " В-31",
          DAY: "5",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Головина И.В.",
          POST: " Экономика",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " В-31",
          DAY: "6",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ершов В.В.",
          POST: "Метрология, СиС",
          NAME: " лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "В-31",
          DAY: "6",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ткачук Е.О.",
          POST: " Выч. математика",
          NAME: " лек.",
          SUBJECT: "12-09-2020каф. ИВТ",
        },
        {
          GROUP: " В-31",
          DAY: "6",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ткачук Е.О.",
          POST: " Выч. математика",
          NAME: " ПЗ",
          SUBJECT: "12-09-2020каф. ИВТ",
        },
        {
          GROUP: " В-31",
          DAY: "7",
          LES: " 1",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Кузин А.П.",
          POST: "Периферийные устройства и интерфейсы",
          NAME: "лек.",
          SUBJECT: "13-09-2020каф. ИВТ",
        },
        {
          GROUP: " В-31",
          DAY: "7",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Кузин А.П.",
          POST: "Периферийные устройства и интерфейсы",
          NAME: "лек.",
          SUBJECT: "13-09-2020каф. ИВТ",
        },
        {
          GROUP: " В-31",
          DAY: "7",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Кузин А.П.",
          POST: "Периферийные устройства и интерфейсы",
          NAME: "ПЗ",
          SUBJECT: "13-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 1",
          LES: " 4",
          AUD: " 217",
          WEEK: " 2",
          SUBG: " Манин А.А.",
          POST: "Методы и средства ЗКИ",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДП-41",
          DAY: " 1",
          LES: " 5",
          AUD: " 217",
          WEEK: " 2",
          SUBG: " Манин А.А.",
          POST: "Методы и средства ЗКИ",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДП-41",
          DAY: " 2",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Головина И.В.",
          POST: " Экономика",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДП-41",
          DAY: " 2",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Головина И.В.",
          POST: " Экономика",
          NAME: " ПЗ",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДП-41",
          DAY: " 3",
          LES: " 4",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Разработка кроссплатформ. прил. С++",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 3",
          LES: " 5",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Разработка кроссплатформ. прил. С++",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 3",
          LES: " 6",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Лобзенко П.В.",
          POST: " Разработка кроссплатформ. прил. С++",
          NAME: " ПЗ",
          SUBJECT: "9-09-2020 каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 4",
          LES: " 4",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Кузин А.П.",
          POST: "Объектно-ориентир. программирование",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 4",
          LES: " 5",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Кузин А.П.",
          POST: "Объектно-ориентир. программирование",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 4",
          LES: " 6",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Кузин А.П.",
          POST: "Объектно-ориентир. программирование",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 5",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Головина И.В.",
          POST: " Экономика",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДП-41",
          DAY: " 5",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Головина И.В.",
          POST: " Экономика",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ДП-41",
          DAY: " 6",
          LES: " 2",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Кузин А.П.",
          POST: "WEB - программирование",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 6",
          LES: " 3",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Кузин А.П.",
          POST: "WEB - программирование",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДП-41",
          DAY: " 6",
          LES: " 4",
          AUD: " 218",
          WEEK: " 2",
          SUBG: " Кузин А.П.",
          POST: "WEB - программирование",
          NAME: "ПЗ",
          SUBJECT: "12-09-2020каф. ИВТ",
        },
        {
          GROUP: " ДЗ-41",
          DAY: " 1",
          LES: " 4",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Жуковский Д.А.",
          POST: "Маркетинг в отр. ИК",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДЗ-41",
          DAY: " 1",
          LES: " 5",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Жуковский Д.А.",
          POST: "Маркетинг в отр. ИК",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ДЗ-41",
          DAY: " 2",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ершов В.В.",
          POST: "Эл.питание УиС ТК",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 2",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ершов В.В.",
          POST: "Эл.питание УиС ТК",
          NAME: " ЛР",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 2",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Эл.питание УиС ТК",
          NAME: " ЛР",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 2",
          LES: " 6",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ершов В.В.",
          POST: "Эл.питание УиС ТК",
          NAME: " ЛР",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 2",
          LES: " 6",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Эл.питание УиС ТК",
          NAME: " ЛР",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 3",
          LES: " 4",
          AUD: " 312",
          WEEK: " 2",
          SUBG: " Енгибарян И.А.",
          POST: "Многоканал. ЦСПиСЗ",
          NAME: "ПЗ",
          SUBJECT: "9-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 3",
          LES: " 5",
          AUD: " 312",
          WEEK: " 2",
          SUBG: " Енгибарян И.А.",
          POST: "Многоканал. ЦСПиСЗ",
          NAME: "ПЗ",
          SUBJECT: "9-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 4",
          LES: " 4",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Болдырихин Н.В.",
          POST: " Сети и сист. радиосв. и СИЗ",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 4",
          LES: " 5",
          AUD: " 220",
          WEEK: " 2",
          SUBG: " Болдырихин Н.В.",
          POST: " Сети и сист. радиосв. и СИЗ",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 4",
          LES: " 6",
          AUD: " 217",
          WEEK: " 2",
          SUBG: " Болдырихин Н.В.",
          POST: " Сети и сист. радиосв. и СИЗ",
          NAME: " ПЗ",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 5",
          LES: " 4",
          AUD: " 217",
          WEEK: " 2",
          SUBG: " Сосновский И.А.",
          POST: " Сети электросвязи и МЗ",
          NAME: "лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ДЗ-41",
          DAY: " 5",
          LES: " 5",
          AUD: " 217",
          WEEK: " 2",
          SUBG: " Сосновский И.А.",
          POST: " Сети электросвязи и МЗ",
          NAME: "лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 1",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " деканат",
          POST: " СОБРАНИЕ",
          NAME: "лек.",
          SUBJECT: "7-09-2020 дек",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 1",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-41",
          DAY: " 1",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Рыбалко И.П.",
          POST: "Осн. криптографии",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 1",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Направл. среды СЭиМЗ",
          NAME: "лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 2",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Манин А.А.",
          POST: "Методы и средства ЗКИ",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 2",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-41",
          DAY: " 3",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-41",
          DAY: " 3",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-41",
          DAY: " 4",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Маркетинг в отр. ИК",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ЗС-41",
          DAY: " 4",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Манин А.А.",
          POST: "Методы и средства ЗКИ",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 4",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Рыбалко И.П.",
          POST: "Осн. криптографии",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 5",
          LES: " 1",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Направл. среды СЭиМЗ",
          NAME: "лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 5",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский А.Г.",
          POST: "Сети и сист. радиосв. и СИЗ",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 5",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский А.Г.",
          POST: "Сети и сист. радиосв. и СИЗ",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 6",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Многоканал. ЦСПиСЗ",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-41",
          DAY: " 6",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Многоканал. ЦСПиСЗ",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 1",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " деканат",
          POST: " СОБРАНИЕ",
          NAME: "лек.",
          SUBJECT: "7-09-2020 дек",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 1",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 1",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Рыбалко И.П.",
          POST: "Осн. криптографии",
          NAME: " лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 1",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Направл. среды СЭиМЗ",
          NAME: "лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 2",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Манин А.А.",
          POST: "Методы и средства ЗКИ",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 2",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 2",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "ПЗ",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 3",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 3",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 3",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "ПЗ",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 4",
          LES: " 1",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "ПЗ",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 4",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Маркетинг в отр. ИК",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 4",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Манин А.А.",
          POST: "Методы и средства ЗКИ",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 4",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Рыбалко И.П.",
          POST: "Осн. криптографии",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 5",
          LES: " 1",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Направл. среды СЭиМЗ",
          NAME: "лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 5",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский А.Г.",
          POST: "Сети и сист. радиосв. и СИЗ",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 5",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский А.Г.",
          POST: "Сети и сист. радиосв. и СИЗ",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 5",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "ПЗ",
          SUBJECT: "11-09-2020каф. ОНП",
        },
        {
          GROUP: " ЗС-42",
          DAY: " 6",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Многоканал. ЦСПиСЗ",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 6",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Многоканал. ЦСПиСЗ",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "ЗС-42",
          DAY: " 6",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Многоканал. ЦСПиСЗ",
          NAME: "ПЗ",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "1",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " деканат",
          POST: " СОБРАНИЕ",
          NAME: "лек.",
          SUBJECT: "7-09-2020 дек",
        },
        {
          GROUP: "М-41",
          DAY: "1",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " М-41",
          DAY: "2",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Борисов Б.П.",
          POST: "Методы и СИ в ТКС",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "2",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Борисов Б.П.",
          POST: "Методы и СИ в ТКС",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "2",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " М-41",
          DAY: "3",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " М-41",
          DAY: "3",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " М-41",
          DAY: "3",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Решетникова И.В.",
          POST: "Сети связи и СК",
          NAME: " лек.",
          SUBJECT: "9-09-2020 каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "4",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Маркетинг в отр. ИК",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " М-41",
          DAY: "4",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Направл. среды эл.связи",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "5",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Борисов Б.П.",
          POST: "Многоканал. ТКС",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "5",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Борисов Б.П.",
          POST: "Многоканал. ТКС",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "5",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Направл. среды эл.связи",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "6",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ершов В.В.",
          POST: "Метрология, СиС в ИК",
          NAME: "ЛР",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "6",
          LES: " 3",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Манин А.А",
          POST: " Метрология, СиС в ИК",
          NAME: "ЛР",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "6",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Ершов В.В.",
          POST: "Метрология, СиС в ИК",
          NAME: "ЛР",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "М-41",
          DAY: "6",
          LES: " 4",
          AUD: " +",
          WEEK: " 2",
          SUBG: " Манин А.А",
          POST: " Метрология, СиС в ИК",
          NAME: "ЛР",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "1",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " деканат",
          POST: " СОБРАНИЕ",
          NAME: "лек.",
          SUBJECT: "7-09-2020 дек",
        },
        {
          GROUP: "С-41",
          DAY: "1",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "7-09-2020 каф. ОНП",
        },
        {
          GROUP: " С-41",
          DAY: "1",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Решетникова И.В.",
          POST: "Системы коммутации",
          NAME: "лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "1",
          LES: " 5",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Решетникова И.В.",
          POST: "Системы коммутации",
          NAME: "лек.",
          SUBJECT: "7-09-2020 каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "2",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Цифровые СП",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "2",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Енгибарян И.А.",
          POST: "Направл. среды эл.связи",
          NAME: " лек.",
          SUBJECT: "8-09-2020 каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "2",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "лек.",
          SUBJECT: "8-09-2020 каф. ОНП",
        },
        {
          GROUP: " С-41",
          DAY: "3",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " С-41",
          DAY: "3",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Производ. менеджмент",
          NAME: "лек.",
          SUBJECT: "9-09-2020 каф. ОНП",
        },
        {
          GROUP: " С-41",
          DAY: "4",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Маркетинг в отр. ИК",
          NAME: " лек.",
          SUBJECT: "10-09-2020каф. ОНП",
        },
        {
          GROUP: " С-41",
          DAY: "4",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Решетникова И.В.",
          POST: "Системы коммутации",
          NAME: "лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "4",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Решетникова И.В.",
          POST: "Системы коммутации",
          NAME: "лек.",
          SUBJECT: "10-09-2020каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "5",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Цифровые СП",
          NAME: " лек.",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "5",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Цифровые СП",
          NAME: " ПЗ",
          SUBJECT: "11-09-2020каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "6",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Нерсесянц А.А.",
          POST: "Теория телетрафика",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "6",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Нерсесянц А.А.",
          POST: "Теория телетрафика",
          NAME: "лек.",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "6",
          LES: " 4",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Герасимов И.Н.",
          POST: "Цифровые СП",
          NAME: " ПЗ",
          SUBJECT: "12-09-2020каф. ИТСС",
        },
        {
          GROUP: "С-41",
          DAY: "7",
          LES: " 2",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "ПЗ",
          SUBJECT: "13-09-2020каф. ОНП",
        },
        {
          GROUP: " С-41",
          DAY: "7",
          LES: " 3",
          AUD: " ДО",
          WEEK: "2",
          SUBG: " Жуковский Д.А.",
          POST: "Искусство дел. отнош",
          NAME: "ПЗ",
          SUBJECT: "13-09-2020каф. ОНП",
        },
      ],
      groupSched: [],
      groupSchedByDays: [],
    };
  },
  methods: {
    sortBy(arr) {
      const output = [];
      let last = 0;
      for (let i = 1; i <= arr.length; i++) {
        if (arr[i]?.DAY !== arr[i - 1]?.DAY) {
          output.push(arr.slice(last, i));
          last = i;
        }
      }
      return output;
    },
    getSchedByGroup(name) {
      this.groupSched = [];
      let sortSchedByDays = [];
      this.sched.forEach((element) => {
        if (element.GROUP === name) this.groupSched.push(element);
      });
      this.groupSchedByDays = this.sortBy(this.groupSched);
      console.log(this.groupSchedByDays);
      this.showSched = true;
    },
    getSchedAll() {
      this.groupSched = [];
      let obj = {};
      this.sched.forEach((element) => {
        obj[element.GROUP] = element;
      });
      this.keys = [...new Set(this.sched.map(({ GROUP }) => GROUP))];
      this.showSched = false;
    },
  },
  created: function () {
    this.getSchedAll();
  },
};
</script>

<style lang="css">
.sched-container {
  display: flex;
  justify-content: space-around;
  flex-wrap: wrap;
  flex-direction: row;
}

.sched-container v-col {
  width: 150px;
}
v-card {
  width: 150px;
}
header {
  display: flex;
  justify-content: center;
  flex-direction: row;
  align-items: center;
}
header .card {
  margin: 12px;
}
.sched-card {
  text-align: center;
  padding: 12px;
  margin-bottom: 8px;
}
.group-card {
  padding: 24px;
  margin: 12px;
}
</style>
